### ISSUE TITLE
Flat world type

### ISSUE THREAD

**Issue by jimerrills** [MelanX/DefaultWorldType#9]
### Minecraft version

1.20.x

### Default World Type version

1.20.1-4.0.5

### NeoForge version

forge-47.3.7

### The latest.log file

N/A

### Issue description

When making a superflat world, it seems to make the nether/end superflat as well. This does not happen with the standard superflat generation with minecraft.

Is there a way i can avoid this?

**Comment by MelanX** [comment]
First of all: where did you get 4.0.5 from? This doesn't exist.
Second: Sadly, I can't reproduce it. I changed the config:
```toml
[world-preset]
	#Type in the name from the world type which should be selected by default.
	world-preset = "minecraft:flat"
	#Type in a valid generation setting for flat world type.
	#Only works if world-type if 'minecraft:flat'.
	flat-settings = "minecraft:bedrock,2*minecraft:dirt,minecraft:grass_block;minecraft:plains"
```

The result was: normal nether, normal end, flat overworld. What did you do?
